///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace UserCodeTest.Modules
{
    public partial class FirstStepNewPW
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
        					/// Choose "I will enter/paste in my data"
        					
            Report.Log(ReportLevel.Info,"Mouse", "Left Click CheckBox", new RecordItemIndex(0));
            repo.NewProtocolWizard.SomeContainer.OptionMark.Click();
            				
            							/// Click next button
            
            Report.Log(ReportLevel.Info, "Mouse", "Left Click Button 'Next'", new RecordItemIndex(1));
            repo.NewProtocolWizard.SomeContainer.Next.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Left Click Button 'Next'", new RecordItemIndex(2));
            repo.NewProtocolWizard.SomeContainer.Next.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Left Click Button 'Next'", new RecordItemIndex(3));
            repo.NewProtocolWizard.SomeContainer.Next.Click();
            
            								/// Click Manage Types
            
            Report.Log(ReportLevel.Info, "Mouse", "Left Click Button 'Manage Types'", new RecordItemIndex(4));
            repo.NewProtocolWizard.SomeContainer.AdvancedViewButton.Click();
            
            
            
        }

    }
}