///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace UserCodeTest.Modules
{
    public partial class OpenMaeCreateNewP
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
        	Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe'", new RecordItemIndex(0));
        	Host.Local.RunApplication("C:\\Program Files (x86)\\MyAssays\\MyAssays Desktop\\MyAssays.Desktop.Explorer.exe");
        	Delay.Seconds(10);
        				///  click button "Protocol"
        	
        	Report.Log(ReportLevel.Info, "mouse", "Left Click button 'Protocols'", new RecordItemIndex(1));
        	repo.MyAssaysExplorer.Protocols.Click();
        	
        				/// click button "New"
        	
        	Report.Log(ReportLevel.Info, "Mouse", "Left Click button 'New'", new RecordItemIndex(2));
        	repo.MyAssaysExplorer.InnerPath.Click();
        	
        }

    }
}