///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UserCodeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the UserCodeTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("72af19fe-e8cc-4951-b570-5576efa03ac8")]
    public partial class UserCodeTestRepository : RepoGenBaseFolder
    {
        static UserCodeTestRepository instance = new UserCodeTestRepository();
        UserCodeTestRepositoryFolders.NewProtocolWizardAppFolder _newprotocolwizard;
        UserCodeTestRepositoryFolders.MyAssaysExplorerAppFolder _myassaysexplorer;
        UserCodeTestRepositoryFolders.SampleTypesEditorAppFolder _sampletypeseditor;
        UserCodeTestRepositoryFolders.SampleTypesEditor1AppFolder _sampletypeseditor1;

        /// <summary>
        /// Gets the singleton class instance representing the UserCodeTestRepository element repository.
        /// </summary>
        [RepositoryFolder("72af19fe-e8cc-4951-b570-5576efa03ac8")]
        public static UserCodeTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public UserCodeTestRepository() 
            : base("UserCodeTestRepository", "/", null, 0, false, "72af19fe-e8cc-4951-b570-5576efa03ac8", ".\\RepositoryImages\\UserCodeTestRepository72af19fe.rximgres")
        {
            _newprotocolwizard = new UserCodeTestRepositoryFolders.NewProtocolWizardAppFolder(this);
            _myassaysexplorer = new UserCodeTestRepositoryFolders.MyAssaysExplorerAppFolder(this);
            _sampletypeseditor = new UserCodeTestRepositoryFolders.SampleTypesEditorAppFolder(this);
            _sampletypeseditor1 = new UserCodeTestRepositoryFolders.SampleTypesEditor1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("72af19fe-e8cc-4951-b570-5576efa03ac8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The NewProtocolWizard folder.
        /// </summary>
        [RepositoryFolder("aefa37ac-3245-4ed0-837c-41daa1049d90")]
        public virtual UserCodeTestRepositoryFolders.NewProtocolWizardAppFolder NewProtocolWizard
        {
            get { return _newprotocolwizard; }
        }

        /// <summary>
        /// The MyAssaysExplorer folder.
        /// </summary>
        [RepositoryFolder("33c808e2-78bd-40ee-b0b5-36f68f045fe3")]
        public virtual UserCodeTestRepositoryFolders.MyAssaysExplorerAppFolder MyAssaysExplorer
        {
            get { return _myassaysexplorer; }
        }

        /// <summary>
        /// The SampleTypesEditor folder.
        /// </summary>
        [RepositoryFolder("cb3a9541-0249-48e0-b7db-c230f37c9e18")]
        public virtual UserCodeTestRepositoryFolders.SampleTypesEditorAppFolder SampleTypesEditor
        {
            get { return _sampletypeseditor; }
        }

        /// <summary>
        /// The SampleTypesEditor1 folder.
        /// </summary>
        [RepositoryFolder("ffee9dfd-a702-4284-9412-14c277025863")]
        public virtual UserCodeTestRepositoryFolders.SampleTypesEditor1AppFolder SampleTypesEditor1
        {
            get { return _sampletypeseditor1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class UserCodeTestRepositoryFolders
    {
        /// <summary>
        /// The NewProtocolWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("aefa37ac-3245-4ed0-837c-41daa1049d90")]
        public partial class NewProtocolWizardAppFolder : RepoGenBaseFolder
        {
            UserCodeTestRepositoryFolders.SomeContainerFolder _somecontainer;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new NewProtocolWizard  folder.
            /// </summary>
            public NewProtocolWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewProtocolWizard", "/form[@wpfnative='True' and @title='New Protocol Wizard' and @processname='MyAssays.Desktop.Explorer']", parentFolder, 15000, null, true, "aefa37ac-3245-4ed0-837c-41daa1049d90", "")
            {
                _somecontainer = new UserCodeTestRepositoryFolders.SomeContainerFolder(this);
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Закрити']", 15000, null, "6199deab-bee2-40df-a4a2-4fd8a82c773f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aefa37ac-3245-4ed0-837c-41daa1049d90")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aefa37ac-3245-4ed0-837c-41daa1049d90")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("6199deab-bee2-40df-a4a2-4fd8a82c773f")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("6199deab-bee2-40df-a4a2-4fd8a82c773f")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The SomeContainer folder.
            /// </summary>
            [RepositoryFolder("fd6e3413-e1ec-4e53-922e-b5f86505e64e")]
            public virtual UserCodeTestRepositoryFolders.SomeContainerFolder SomeContainer
            {
                get { return _somecontainer; }
            }
        }

        /// <summary>
        /// The SomeContainerFolder folder.
        /// </summary>
        [RepositoryFolder("fd6e3413-e1ec-4e53-922e-b5f86505e64e")]
        public partial class SomeContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextInfo;
            RepoItemInfo _advancedviewbuttonInfo;
            RepoItemInfo _optionmarkInfo;
            RepoItemInfo _test00Info;

            /// <summary>
            /// Creates a new SomeContainer  folder.
            /// </summary>
            public SomeContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer", "element/container", parentFolder, 15000, null, false, "fd6e3413-e1ec-4e53-922e-b5f86505e64e", "")
            {
                _nextInfo = new RepoItemInfo(this, "Next", "container[1]/container/button[@text='Next']", 15000, null, "b900e1dd-b4ac-4a77-b0ed-f8b053fa70f5");
                _advancedviewbuttonInfo = new RepoItemInfo(this, "AdvancedViewButton", "element/container/container/container/container/button[@automationid='AdvancedViewButton']", 15000, null, "d1fb6311-b77c-460d-9360-0012882061ca");
                _optionmarkInfo = new RepoItemInfo(this, "OptionMark", "element/container/container/container[1]/radiobutton[@text='I will enter/paste in my data']/element[@automationid='optionMark']", 15000, null, "e08ea199-0f0b-4af4-8965-1fbe14edfa4c");
                _test00Info = new RepoItemInfo(this, "Test00", "element/container/container/container/?/?/list[@automationid='SampleTypesSimplifiedView']/container/checkbox[10]/container[2]/text[@caption='Test00']", 15000, null, "73b861c2-f866-4c15-a539-1351861ed7c4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd6e3413-e1ec-4e53-922e-b5f86505e64e")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd6e3413-e1ec-4e53-922e-b5f86505e64e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("b900e1dd-b4ac-4a77-b0ed-f8b053fa70f5")]
            public virtual Ranorex.Button Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("b900e1dd-b4ac-4a77-b0ed-f8b053fa70f5")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The AdvancedViewButton item.
            /// </summary>
            [RepositoryItem("d1fb6311-b77c-460d-9360-0012882061ca")]
            public virtual Ranorex.Button AdvancedViewButton
            {
                get
                {
                    return _advancedviewbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AdvancedViewButton item info.
            /// </summary>
            [RepositoryItemInfo("d1fb6311-b77c-460d-9360-0012882061ca")]
            public virtual RepoItemInfo AdvancedViewButtonInfo
            {
                get
                {
                    return _advancedviewbuttonInfo;
                }
            }

            /// <summary>
            /// The OptionMark item.
            /// </summary>
            [RepositoryItem("e08ea199-0f0b-4af4-8965-1fbe14edfa4c")]
            public virtual Ranorex.Unknown OptionMark
            {
                get
                {
                    return _optionmarkInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The OptionMark item info.
            /// </summary>
            [RepositoryItemInfo("e08ea199-0f0b-4af4-8965-1fbe14edfa4c")]
            public virtual RepoItemInfo OptionMarkInfo
            {
                get
                {
                    return _optionmarkInfo;
                }
            }

            /// <summary>
            /// The Test00 item.
            /// </summary>
            [RepositoryItem("73b861c2-f866-4c15-a539-1351861ed7c4")]
            public virtual Ranorex.Text Test00
            {
                get
                {
                    return _test00Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Test00 item info.
            /// </summary>
            [RepositoryItemInfo("73b861c2-f866-4c15-a539-1351861ed7c4")]
            public virtual RepoItemInfo Test00Info
            {
                get
                {
                    return _test00Info;
                }
            }
        }

        /// <summary>
        /// The MyAssaysExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("33c808e2-78bd-40ee-b0b5-36f68f045fe3")]
        public partial class MyAssaysExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _protocolsInfo;
            RepoItemInfo _innerpathInfo;
            RepoItemInfo _quitInfo;

            /// <summary>
            /// Creates a new MyAssaysExplorer  folder.
            /// </summary>
            public MyAssaysExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyAssaysExplorer", "/form[@wpfnative='True' and @title='MyAssays Explorer' and @processname='MyAssays.Desktop.Explorer']", parentFolder, 15000, null, true, "33c808e2-78bd-40ee-b0b5-36f68f045fe3", "")
            {
                _protocolsInfo = new RepoItemInfo(this, "Protocols", "container/container/container/container/container/container[2]/tabpagelist[@automationid='TabControl']/tabpage[@index='2']/container[@automationid='PART_DockPanel']/text[@caption='Protocols']", 15000, null, "7e2ecb3a-f096-4142-b4a8-f65cea2d26ac");
                _innerpathInfo = new RepoItemInfo(this, "InnerPath", "container//list[@automationid='Ribbon']/list[1]/list[3]/element[@automationid='NewFileRibbonButton']/?/?/element[@automationid='InnerPath']", 15000, null, "e54e6116-5238-4120-be07-9e2315042e3e");
                _quitInfo = new RepoItemInfo(this, "Quit", "?/?/button[@accessiblename='Закрити']", 15000, null, "0c122a06-8472-4d6b-a39f-0741a7581e96");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("33c808e2-78bd-40ee-b0b5-36f68f045fe3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("33c808e2-78bd-40ee-b0b5-36f68f045fe3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Protocols item.
            /// </summary>
            [RepositoryItem("7e2ecb3a-f096-4142-b4a8-f65cea2d26ac")]
            public virtual Ranorex.Text Protocols
            {
                get
                {
                    return _protocolsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Protocols item info.
            /// </summary>
            [RepositoryItemInfo("7e2ecb3a-f096-4142-b4a8-f65cea2d26ac")]
            public virtual RepoItemInfo ProtocolsInfo
            {
                get
                {
                    return _protocolsInfo;
                }
            }

            /// <summary>
            /// The InnerPath item.
            /// </summary>
            [RepositoryItem("e54e6116-5238-4120-be07-9e2315042e3e")]
            public virtual Ranorex.Unknown InnerPath
            {
                get
                {
                    return _innerpathInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The InnerPath item info.
            /// </summary>
            [RepositoryItemInfo("e54e6116-5238-4120-be07-9e2315042e3e")]
            public virtual RepoItemInfo InnerPathInfo
            {
                get
                {
                    return _innerpathInfo;
                }
            }

            /// <summary>
            /// The Quit item.
            /// </summary>
            [RepositoryItem("0c122a06-8472-4d6b-a39f-0741a7581e96")]
            public virtual Ranorex.Button Quit
            {
                get
                {
                    return _quitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Quit item info.
            /// </summary>
            [RepositoryItemInfo("0c122a06-8472-4d6b-a39f-0741a7581e96")]
            public virtual RepoItemInfo QuitInfo
            {
                get
                {
                    return _quitInfo;
                }
            }
        }

        /// <summary>
        /// The SampleTypesEditorAppFolder folder.
        /// </summary>
        [RepositoryFolder("cb3a9541-0249-48e0-b7db-c230f37c9e18")]
        public partial class SampleTypesEditorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addsampletypeInfo;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _togglebuttonInfo;
            RepoItemInfo _calibratorInfo;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _text0Info;
            RepoItemInfo _selectedcolortextInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _test00Info;

            /// <summary>
            /// Creates a new SampleTypesEditor  folder.
            /// </summary>
            public SampleTypesEditorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SampleTypesEditor", "/form[@wpfnative='True' and @title='Sample Types Editor' and @processname='MyAssays.Desktop.Explorer']", parentFolder, 15000, null, true, "cb3a9541-0249-48e0-b7db-c230f37c9e18", "")
            {
                _addsampletypeInfo = new RepoItemInfo(this, "AddSampleType", "container/?/?/button[@text='Add Sample Type']", 15000, null, "1cdcdcc4-c163-47f0-8bcc-0917e7882ed4");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "container/?/?/list[@automationid='SampleTypesSimplifiedView']/container/container[10]/text/element[2]", 15000, null, "210e175b-0929-4fdb-8ed9-4f9c557cc1b9");
                _togglebuttonInfo = new RepoItemInfo(this, "ToggleButton", ".//list[@automationid='SampleTypesSimplifiedView']/container/container[10]/?/?/combobox/container[@automationid='templateRoot']/checkbox[@automationid='toggleButton']", 15000, null, "b9bc7559-3812-4326-86a0-18718b4fbffe");
                _calibratorInfo = new RepoItemInfo(this, "Calibrator", ".//list[@automationid='SampleTypesSimplifiedView']/container/container[10]/?/?/combobox/container[@automationid='templateRoot']/contextmenu[@automationid='PART_Popup']/?/?/container[@automationid='grid']/?/?/listitem[@text='Calibrator']", 15000, null, "49d72749-31db-48e4-900f-7f59a1feee39");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "container/?/?/list[@automationid='SampleTypesSimplifiedView']/container/container[10]//checkbox[@automationid='colorToggleButton']/container", 15000, null, "80345235-34ed-4d22-9219-027b0b8f0477");
                _text0Info = new RepoItemInfo(this, "Text0", "container/container[1]/container/list[@automationid='SampleTypesSimplifiedView']/container/container[10]//contextmenu[@automationid='colorEditPopup']/?/?/element[@automationid='ColorEdit']/container/container[3]/text[5]", 15000, null, "2bf7dce5-ef2b-4f2b-9179-2eb5ebcc4a24");
                _selectedcolortextInfo = new RepoItemInfo(this, "SelectedColorText", "container/container[1]/list[@automationid='SampleTypesSimplifiedView']/container/container[10]//checkbox[@automationid='colorToggleButton']//text[@automationid='SelectedColorText']", 15000, null, "44bfcc0b-f16b-403a-930e-9ebf9b16be52");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container/?/?/button[@text='OK']", 15000, null, "70d45067-9722-40f1-a918-7be15e3aa9d9");
                _test00Info = new RepoItemInfo(this, "Test00", ".//list[@automationid='SampleTypesSimplifiedView']/container/container[10]/text[@caption='Test00']", 15000, null, "40fe0ee0-9ed5-4266-b84f-e341fc151ed5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cb3a9541-0249-48e0-b7db-c230f37c9e18")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb3a9541-0249-48e0-b7db-c230f37c9e18")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddSampleType item.
            /// </summary>
            [RepositoryItem("1cdcdcc4-c163-47f0-8bcc-0917e7882ed4")]
            public virtual Ranorex.Button AddSampleType
            {
                get
                {
                    return _addsampletypeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddSampleType item info.
            /// </summary>
            [RepositoryItemInfo("1cdcdcc4-c163-47f0-8bcc-0917e7882ed4")]
            public virtual RepoItemInfo AddSampleTypeInfo
            {
                get
                {
                    return _addsampletypeInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("210e175b-0929-4fdb-8ed9-4f9c557cc1b9")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("210e175b-0929-4fdb-8ed9-4f9c557cc1b9")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The ToggleButton item.
            /// </summary>
            [RepositoryItem("b9bc7559-3812-4326-86a0-18718b4fbffe")]
            public virtual Ranorex.CheckBox ToggleButton
            {
                get
                {
                    return _togglebuttonInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ToggleButton item info.
            /// </summary>
            [RepositoryItemInfo("b9bc7559-3812-4326-86a0-18718b4fbffe")]
            public virtual RepoItemInfo ToggleButtonInfo
            {
                get
                {
                    return _togglebuttonInfo;
                }
            }

            /// <summary>
            /// The Calibrator item.
            /// </summary>
            [RepositoryItem("49d72749-31db-48e4-900f-7f59a1feee39")]
            public virtual Ranorex.ListItem Calibrator
            {
                get
                {
                    return _calibratorInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Calibrator item info.
            /// </summary>
            [RepositoryItemInfo("49d72749-31db-48e4-900f-7f59a1feee39")]
            public virtual RepoItemInfo CalibratorInfo
            {
                get
                {
                    return _calibratorInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("80345235-34ed-4d22-9219-027b0b8f0477")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("80345235-34ed-4d22-9219-027b0b8f0477")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The Text0 item.
            /// </summary>
            [RepositoryItem("2bf7dce5-ef2b-4f2b-9179-2eb5ebcc4a24")]
            public virtual Ranorex.Text Text0
            {
                get
                {
                    return _text0Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text0 item info.
            /// </summary>
            [RepositoryItemInfo("2bf7dce5-ef2b-4f2b-9179-2eb5ebcc4a24")]
            public virtual RepoItemInfo Text0Info
            {
                get
                {
                    return _text0Info;
                }
            }

            /// <summary>
            /// The SelectedColorText item.
            /// </summary>
            [RepositoryItem("44bfcc0b-f16b-403a-930e-9ebf9b16be52")]
            public virtual Ranorex.Text SelectedColorText
            {
                get
                {
                    return _selectedcolortextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SelectedColorText item info.
            /// </summary>
            [RepositoryItemInfo("44bfcc0b-f16b-403a-930e-9ebf9b16be52")]
            public virtual RepoItemInfo SelectedColorTextInfo
            {
                get
                {
                    return _selectedcolortextInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("70d45067-9722-40f1-a918-7be15e3aa9d9")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("70d45067-9722-40f1-a918-7be15e3aa9d9")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Test00 item.
            /// </summary>
            [RepositoryItem("40fe0ee0-9ed5-4266-b84f-e341fc151ed5")]
            public virtual Ranorex.Text Test00
            {
                get
                {
                    return _test00Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Test00 item info.
            /// </summary>
            [RepositoryItemInfo("40fe0ee0-9ed5-4266-b84f-e341fc151ed5")]
            public virtual RepoItemInfo Test00Info
            {
                get
                {
                    return _test00Info;
                }
            }
        }

        /// <summary>
        /// The SampleTypesEditor1AppFolder folder.
        /// </summary>
        [RepositoryFolder("ffee9dfd-a702-4284-9412-14c277025863")]
        public partial class SampleTypesEditor1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonInfo;

            /// <summary>
            /// Creates a new SampleTypesEditor1  folder.
            /// </summary>
            public SampleTypesEditor1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SampleTypesEditor1", "/form[@name='Sample Types Editor' and @classname='Window' and @orientation='None']", parentFolder, 15000, null, true, "ffee9dfd-a702-4284-9412-14c277025863", "")
            {
                _buttonInfo = new RepoItemInfo(this, "Button", "container/button[20]", 15000, null, "5c5c8109-cad2-4bf0-855c-60dc13dad33b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ffee9dfd-a702-4284-9412-14c277025863")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ffee9dfd-a702-4284-9412-14c277025863")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("5c5c8109-cad2-4bf0-855c-60dc13dad33b")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("5c5c8109-cad2-4bf0-855c-60dc13dad33b")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}